## Exercise 1: Convert a list and tuple into arrays

In [11]:
import numpy as np
list_array = np.asarray([1, 2, 3 ,4 ,5, 6, 7, 8])
print(list_array)
tuple_array = np.asarray(([8,4,6] ,[1,2,3]))
print(tuple_array)

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


## Also try np.asarray for the problem above! 

## Exercise 2:  Convert the values of Centigrade degrees into Fahrenheit degrees

In [30]:
import numpy as np
values_in_fahren=[ 0,  12,   45.21, 34,   99.91]
arr_in_fahren=np.asarray(values_in_fahreneit)
values_in_centi=5*arr_in_fahren/9 - 5*32/9
print(values_in_centi)
print(np.around(values_in_centi,decimals=2))

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]
[-17.78 -11.11   7.34   1.11  37.73]


## Exercise 3: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

In [47]:
import numpy as np
array_def=np.array([1,2,3])
print(array_def.size)
print(array_def.itemsize)
print(array_def.nbytes)

3
8
24


## Exercise 4: Get the unique elements of an array

In [4]:
import numpy as np
array1=np.array([10, 10, 20, 20, 30 ,30])
print(np.unique(array1))
array2=np.array([[1, 1], [2 ,3]])
print(np.unique(array2))

[10 20 30]
[1 2 3]


## Exercise 5: Change the dimension of an array


In [6]:
import numpy as np
array2=np.array([1, 2 ,3 ,4 ,5, 6 ,7 ,8, 9])
array2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Exercise 6: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [7]:
import numpy as np
array2=np.linspace(2.5,6.5,30)
print(array2)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


## Exercise 7: Convert 1-D arrays as columns into a 2-D array

In [12]:
import numpy as np
a1 = np.array([10, 20, 30])()
a2 = np.array([40, 50, 60])
a3 = np.column_stack((a1,a2))
print(a3)

[[10 40]
 [20 50]
 [30 60]]


## Exercise 8: Create a 5x5 matrix with row values ranging from 0 to 4

In [23]:
import numpy as np
a1 = np.zeros((5,5))
print(np.arange(5))
a1 += np.arange(5)
print(a1)

[0 1 2 3 4]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 9: Sum of all the multiples of 3 or 5 below 100

In [2]:
import numpy as np
a3=np.arange(3,100,3)
a5=np.arange(5,100,5)
ac1=np.concatenate((a3, a5))
print('number of multiples 3 or 5 :',ac1.size)
au1_ele=np.unique(ac1)
print('unique multiples 3 or 5 :',au1_ele.size)
au1=np.unique(ac1).sum()
print('sum',au1)



number of multiples 3 or 5 : 52
unique multiples 3 or 5 : 46
sum 2318
2318


## Exercise 10: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [28]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


In [50]:
import numpy as np
x=np.arange(4)
y=np.arange(8)
z=y.reshape(2,4)
print('One dimensional array:')
print(x)
print('Two dimensional array:')
print(z)
for a, b in np.nditer([x,z]):
    print("{}:{}".format(a,b))

One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


## Exercise 11: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [54]:
import numpy as np
oarr=np.array([[0.42436315,0.48558583, 0.32924763],
 [0.7439979,  0.58220701, 0.38213418],
 [0.5097581,  0.34528799, 0.1563123 ]])
oarr=np.where(oarr > .5, .5, oarr)
print(oarr)

[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 12: Add a new row to an empty numpy array

In [26]:
import numpy as np
earr=np.empty([0,0])
print(earr)
arr1=np.array([10,20,30])
arr2=np.array([40,50,60])
earr=np.stack((arr1,arr2))
print(earr)


[]
[[10 20 30]
 [40 50 60]]


## Exercise 13: Write a NumPy program to join a sequence of arrays along a new axis. 

In [44]:
import numpy as np
arr1=np.array([1,2 ,3])
arr2=np.array([2,3 ,4])
print('orginal arrays',arr1,arr2)
print('Sequence of arrays along a new axis:',np.stack((arr1,arr2)))
arr3=[[1], [2], [3]]
arr4=[[2], [3], [4]]
print('Sequence of arrays along a new axis:',np.vstack((arr3,arr4)))

orginal arrays [1 2 3] [2 3 4]
Sequence of arrays along a new axis: [[1 2 3]
 [2 3 4]]
Sequence of arrays along a new axis: [[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
